[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]  
  from = "/s/hello"
  to = "https://wa.me/966501234567?text=%D9%85%D8%B1%D8%AD%D8%A8%D8%A7%D9%8B"
  status = 302

[[redirects]]
  from = "/s/store"  
  to = "https://wa.me/966509876543?text=%D8%A3%D9%87%D9%84%D8%A7%D9%8B"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html" 
  status = 200