[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/redirect"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200